/**
 * @fileoverview gRPC-Web generated client stub for asl
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.6.1
// source: asl.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.asl = require('./asl_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.asl.ASLServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.asl.ASLServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.asl.PingRequest,
 *   !proto.asl.PingResponse>}
 */
const methodDescriptor_ASLService_Ping = new grpc.web.MethodDescriptor(
  '/asl.ASLService/Ping',
  grpc.web.MethodType.UNARY,
  proto.asl.PingRequest,
  proto.asl.PingResponse,
  /**
   * @param {!proto.asl.PingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.asl.PingResponse.deserializeBinary
);


/**
 * @param {!proto.asl.PingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.asl.PingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.asl.PingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.asl.ASLServiceClient.prototype.ping =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/asl.ASLService/Ping',
      request,
      metadata || {},
      methodDescriptor_ASLService_Ping,
      callback);
};


/**
 * @param {!proto.asl.PingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.asl.PingResponse>}
 *     Promise that resolves to the response
 */
proto.asl.ASLServicePromiseClient.prototype.ping =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/asl.ASLService/Ping',
      request,
      metadata || {},
      methodDescriptor_ASLService_Ping);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.asl.TextRequest,
 *   !proto.asl.VideoResponse>}
 */
const methodDescriptor_ASLService_GenerateASLVideo = new grpc.web.MethodDescriptor(
  '/asl.ASLService/GenerateASLVideo',
  grpc.web.MethodType.UNARY,
  proto.asl.TextRequest,
  proto.asl.VideoResponse,
  /**
   * @param {!proto.asl.TextRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.asl.VideoResponse.deserializeBinary
);


/**
 * @param {!proto.asl.TextRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.asl.VideoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.asl.VideoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.asl.ASLServiceClient.prototype.generateASLVideo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/asl.ASLService/GenerateASLVideo',
      request,
      metadata || {},
      methodDescriptor_ASLService_GenerateASLVideo,
      callback);
};


/**
 * @param {!proto.asl.TextRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.asl.VideoResponse>}
 *     Promise that resolves to the response
 */
proto.asl.ASLServicePromiseClient.prototype.generateASLVideo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/asl.ASLService/GenerateASLVideo',
      request,
      metadata || {},
      methodDescriptor_ASLService_GenerateASLVideo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.asl.AudioRequest,
 *   !proto.asl.VideoResponse>}
 */
const methodDescriptor_ASLService_ProcessAudio = new grpc.web.MethodDescriptor(
  '/asl.ASLService/ProcessAudio',
  grpc.web.MethodType.UNARY,
  proto.asl.AudioRequest,
  proto.asl.VideoResponse,
  /**
   * @param {!proto.asl.AudioRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.asl.VideoResponse.deserializeBinary
);


/**
 * @param {!proto.asl.AudioRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.asl.VideoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.asl.VideoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.asl.ASLServiceClient.prototype.processAudio =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/asl.ASLService/ProcessAudio',
      request,
      metadata || {},
      methodDescriptor_ASLService_ProcessAudio,
      callback);
};


/**
 * @param {!proto.asl.AudioRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.asl.VideoResponse>}
 *     Promise that resolves to the response
 */
proto.asl.ASLServicePromiseClient.prototype.processAudio =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/asl.ASLService/ProcessAudio',
      request,
      metadata || {},
      methodDescriptor_ASLService_ProcessAudio);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.asl.AudioRequestForTTS,
 *   !proto.asl.AudioResponse>}
 */
const methodDescriptor_ASLService_GenerateAudio = new grpc.web.MethodDescriptor(
  '/asl.ASLService/GenerateAudio',
  grpc.web.MethodType.UNARY,
  proto.asl.AudioRequestForTTS,
  proto.asl.AudioResponse,
  /**
   * @param {!proto.asl.AudioRequestForTTS} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.asl.AudioResponse.deserializeBinary
);


/**
 * @param {!proto.asl.AudioRequestForTTS} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.asl.AudioResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.asl.AudioResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.asl.ASLServiceClient.prototype.generateAudio =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/asl.ASLService/GenerateAudio',
      request,
      metadata || {},
      methodDescriptor_ASLService_GenerateAudio,
      callback);
};


/**
 * @param {!proto.asl.AudioRequestForTTS} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.asl.AudioResponse>}
 *     Promise that resolves to the response
 */
proto.asl.ASLServicePromiseClient.prototype.generateAudio =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/asl.ASLService/GenerateAudio',
      request,
      metadata || {},
      methodDescriptor_ASLService_GenerateAudio);
};


module.exports = proto.asl;

